# vim:ft=kitty

## name:     Kanagawa Violet
## blurb:    Muted ink palette with subtle violet accents.



# The basic colors
foreground              #DCD7BA
background              #1F1F28
selection_foreground    #1F1F28
selection_background    #DCA561

# Cursor colors
cursor                  #DCA561
cursor_text_color       #1F1F28

# URL underline color when hovering with mouse
url_color               #7E9CD8

# Kitty window border colors
active_border_color     #957FB8
inactive_border_color   #54546D
bell_border_color       #DCA561

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #1F1F28
active_tab_background   #957FB8
inactive_tab_foreground #C8C093
inactive_tab_background #223249
tab_bar_background      #16161D

# Colors for marks (marked text in the terminal)
mark1_foreground #1F1F28
mark1_background #957FB8
mark2_foreground #1F1F28
mark2_background #DCA561
mark3_foreground #1F1F28
mark3_background #7AA89F

# The 16 terminal colors

# black
color0 #16161D
color8 #54546D

# red
color1 #C34043
color9 #E46876

# green
color2  #76946A
color10 #98BB6C

# yellow
color3  #C0A36E
color11 #DCA561

# blue
color4  #7E9CD8
color12 #7FB4CA

# magenta
color5  #957FB8
color13 #A292A3

# cyan
color6  #7AA89F
color14 #7FB4CA

# white
color7  #C8C093
color15 #DCD7BA
